name: Build app and deploy to aliyun
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.15.1'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build

    - name: Upload to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        source: "./dist/*"
        target: /usr/share/nginx/html
    
    # - name: Start Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.SERVER_PRIVATE_KEY }}
    #     script: |
    #       cd /home/ji/robot-serve
    #       pnpm i
    #       pm2 start --name robot-serve npm -- run start:prod
        